version: "3.8"

services:
  nextjs:
    image: node:20
    container_name: nextjs_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_db:5432/${POSTGRES_DB}
    command: sh -c "npm install && npm run dev"

  postgres:
    image: postgres:alpine
    container_name: postgres_db
    env_file:
      - .env.local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
